#!/usr/bin/env bash
# =============================================================
# VAPTBOOSTER — one-shot production deploy (idempotent).
#
# Builds images, brings up the stack, waits for health, installs host deps,
# creates the operator, optionally onboards a tenant, and (optionally) exposes
# the LiteLLM cost dashboard. Safe to re-run.
#
# Run from the repo root, on the server:   bash scripts/deploy-prod.sh
#
# Config — put these in the environment (or a deploy.env you `source` first):
#   OPERATOR_EMAIL / OPERATOR_PASSWORD     create/reset the operator (12+ chars)
#   TENANT_SLUG / TENANT_NAME / TENANT_EMAIL / TENANT_PASSWORD [/ TENANT_PLAN]
#                                          onboard a client tenant + its LLM key
#   LITELLM_PUBLIC=true                    expose the LiteLLM UI publicly on :4000
#                                          (cost dashboard) — else localhost-only
#   PUBLIC_URL=http://1.2.3.4:8080         base URL you'll reach the app at
#                                          (auto-detected if unset)
#   SKIP_BUILD=true                        skip image builds (faster re-deploy)
# =============================================================
set -euo pipefail
cd "$(dirname "$0")/.."

PROD="docker-compose.prod.yml"
OVERRIDE="docker-compose.runner.yml"
COMPOSE="docker compose -f $PROD -f $OVERRIDE"
say() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# ---- 1. Preflight ----------------------------------------------------------
say "Preflight"
command -v docker >/dev/null || die "docker is not installed"
command -v node   >/dev/null || die "node is not installed"
[ -f .env ] || die ".env missing — run: cp .env.production.example .env  (then fill it in)"

REQUIRED=(POSTGRES_PASSWORD APP_DB_PASSWORD REDIS_PASSWORD LITELLM_MASTER_KEY OPENROUTER_API_KEY AUTH_SECRET ROOT_DOMAIN)
for v in "${REQUIRED[@]}"; do
  grep -qE "^${v}=.+" .env || die "missing required var in .env: ${v}"
done
echo "  .env has all required vars"

PUBLIC_IP="$(curl -s -m 5 ifconfig.me 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}')"
APP_URL="${PUBLIC_URL:-http://${PUBLIC_IP}:8080}"

# NextAuth needs the real base URL for cookies over plain HTTP — set it if absent.
if ! grep -qE "^NEXTAUTH_URL=" .env; then
  say "Setting NEXTAUTH_URL/APP_URL in .env → ${APP_URL}"
  { echo "NEXTAUTH_URL=${APP_URL}"; echo "APP_URL=${APP_URL}"; } >> .env
fi

# ---- 2. Compose override: expose postgres (localhost) + litellm ------------
LITELLM_BIND="127.0.0.1"
[ "${LITELLM_PUBLIC:-false}" = "true" ] && LITELLM_BIND="0.0.0.0"
say "Writing ${OVERRIDE} (litellm bind: ${LITELLM_BIND}:4000)"
cat > "$OVERRIDE" <<EOF
# Generated by deploy-prod.sh — postgres on localhost (admin scripts/runner),
# litellm on ${LITELLM_BIND} (cost dashboard). Not committed.
services:
  postgres: { ports: ["127.0.0.1:5432:5432"] }
  litellm:  { ports: ["${LITELLM_BIND}:4000:4000"] }
EOF

# ---- 3. Build ---------------------------------------------------------------
if [ "${SKIP_BUILD:-false}" != "true" ]; then
  say "Building images (web, worker, migrate)"
  $COMPOSE build
  say "Building the agent sandbox image"
  docker build -t vaptbooster-agent-sandbox:latest ./agent-sandbox
fi

# ---- 4. Up + wait for health -----------------------------------------------
say "Bringing up the stack"
$COMPOSE up -d

wait_healthy() {
  local svc="$1" tries="${2:-60}" cid h
  for _ in $(seq 1 "$tries"); do
    cid="$($COMPOSE ps -q "$svc" 2>/dev/null || true)"
    if [ -n "$cid" ]; then
      h="$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$cid" 2>/dev/null || echo none)"
      if [ "$h" = "healthy" ] || [ "$h" = "running" ]; then echo "  $svc: $h"; return 0; fi
    fi
    sleep 3
  done
  return 1
}
say "Waiting for services to become healthy (up to ~3 min)"
wait_healthy litellm 60 || die "litellm did not become healthy — check: $COMPOSE logs litellm"
wait_healthy web 40     || die "web did not become healthy — check: $COMPOSE logs web"
wait_healthy worker 20  || echo "  (worker not confirmed — check logs if scans don't run)"

# ---- 5. Host deps (for admin scripts + the autonomous runner) --------------
say "Installing host deps (npm install — not ci; lockfile omits Linux optional deps)"
npm install --no-audit --no-fund
npx prisma generate
( cd worker && npm install --no-audit --no-fund )

OWNER_DB="postgresql://vaptbooster:$(grep '^POSTGRES_PASSWORD=' .env | cut -d= -f2-)@127.0.0.1:5432/vaptbooster"
MASTER_KEY="$(grep '^LITELLM_MASTER_KEY=' .env | cut -d= -f2-)"

# ---- 6. Operator ------------------------------------------------------------
if [ -n "${OPERATOR_EMAIL:-}" ] && [ -n "${OPERATOR_PASSWORD:-}" ]; then
  say "Creating/updating operator: ${OPERATOR_EMAIL}"
  DATABASE_URL="$OWNER_DB" OPERATOR_EMAIL="$OPERATOR_EMAIL" OPERATOR_PASSWORD="$OPERATOR_PASSWORD" \
    npx tsx scripts/create-operator.ts
else
  echo "  (skip operator — set OPERATOR_EMAIL + OPERATOR_PASSWORD to create one)"
fi

# ---- 7. Tenant onboarding + LLM key ----------------------------------------
if [ -n "${TENANT_SLUG:-}" ]; then
  say "Onboarding tenant: ${TENANT_SLUG}"
  DATABASE_URL="$OWNER_DB" npx tsx scripts/create-tenant.ts \
    "$TENANT_SLUG" "${TENANT_NAME:-$TENANT_SLUG}" "$TENANT_EMAIL" "$TENANT_PASSWORD" "${TENANT_PLAN:-solo}"
  say "Provisioning ${TENANT_SLUG}'s LiteLLM key (budget + cost metering)"
  DATABASE_URL="$OWNER_DB" LITELLM_BASE_URL="http://127.0.0.1:4000" LITELLM_MASTER_KEY="$MASTER_KEY" \
    npx tsx scripts/provision-tenant-key.ts "$TENANT_SLUG"
else
  echo "  (skip tenant — set TENANT_SLUG/NAME/EMAIL/PASSWORD to onboard one)"
fi

# ---- 8. Firewall (best-effort) ---------------------------------------------
if command -v ufw >/dev/null; then
  ufw allow 8080/tcp >/dev/null 2>&1 || true
  [ "$LITELLM_BIND" = "0.0.0.0" ] && ufw allow 4000/tcp >/dev/null 2>&1 || true
fi

# ---- 9. Summary -------------------------------------------------------------
say "Done"
$COMPOSE ps
cat <<EOF

  ┌───────────────────────────────────────────────────────────────
  │ App        : ${APP_URL}
  │ Operator   : ${OPERATOR_EMAIL:-<none created>}
  │ Tenant     : ${TENANT_SLUG:-<none onboarded>}${TENANT_EMAIL:+  (login: ${TENANT_EMAIL})}
  │
  │ 💰 LiteLLM cost dashboard:
EOF
if [ "$LITELLM_BIND" = "0.0.0.0" ]; then
  cat <<EOF
  │   URL   : http://${PUBLIC_IP}:4000/ui     (login: admin / <LITELLM_MASTER_KEY>)
  │   ⚠ PUBLIC — anyone can reach :4000. Firewall it to your IP, or use HTTPS+auth.
EOF
else
  cat <<EOF
  │   localhost-only. Tunnel from your laptop:
  │     ssh -L 4000:127.0.0.1:4000 root@${PUBLIC_IP}
  │   then open http://localhost:4000/ui  (login: admin / <LITELLM_MASTER_KEY>)
EOF
fi
cat <<EOF
  │   API   : curl -s http://127.0.0.1:4000/global/spend -H "Authorization: Bearer <MASTER_KEY>"
  │
  │ ⚠ HTTP only (no TLS) on :8080 — move to 80/443 + TLS before real client logins.
  └───────────────────────────────────────────────────────────────
EOF
